# Generated by Django 2.1.1 on 2018-09-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_auto_20180908_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normal_user_form',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
