# Generated by Django 2.1 on 2018-09-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0005_mesage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesage',
            name='content',
            field=models.TextField(max_length=150),
        ),
    ]
