# Generated by Django 2.1.1 on 2018-09-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0007_auto_20180909_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesage',
            name='approval',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
