# Generated by Django 2.1.1 on 2018-09-12 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0008_mesage_approval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesage',
            options={'ordering': ['-created_time']},
        ),
    ]
